# This conda environment includes everything needed to use pygetm.
# This includes:
# - build and install tools (cmake, a Fortran compiler, cython, pip)
# - an MPI library for parallal simulations
# - support for plotting and postprocessing (matplotlib, cmocean, cartopy)
# - support for interactive simulation (jupyterlab)
# Note: if you are working on a HPC system, you likely want to use
# environment-min.yml instead.
name: pygetm
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - cmake
  - fortran-compiler
  - cython
  - pip
  - mpi4py
  - pyyaml
  - numpy
  - xarray
  - netcdf4
  - scipy
  - matplotlib
  - cmocean
  - cartopy
  - proj
  - jupyterlab
  - ipympl

